language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
  - redis-server
  - sidekiq
before_script:
  - psql -c "CREATE USER qa_thinknetika_app WITH PASSWORD 'qa_qa_app_think';" -U postgres
  - psql -c "CREATE database qa_thinknetika_app_test;" -U postgres
script: bin/rails db:migrate RAILS_ENV=test