language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
  - redis-server
before_script:
  - psql -c "CREATE USER qa_thinknetika_app WITH PASSWORD 'qa_qa_app_think';" -U postgres
  - psql -c "CREATE database qa_thinknetika_app_test;" -U postgres
  # - createdb 'qa_thinknetika_app_test'
# before_script:
#   createdb 'qa_thinknetika_app_test'
#   createuser 'qa_thinknetika_app'
# before_script:
#   - psql -c 'create database travis_ci_test;' -U postgres