
default: &default
  adapter: postgresql
  encoding: utf8
  username: qa_thinknetika_app
  password: qa_qa_app_think
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: qa_thinknetika_app_development


test:
  <<: *default
  database: qa_thinknetika_app_test

production:
  <<: *default
  database: qa_thinknetika_app_production
  
  
