development:
  # server: "http://localhost:9292/faye"
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
test:
  # server: "http://localhost:9292/faye"
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
production:
  # server: "http://localhost:9292/faye"
  server: "http://example.com/faye"
  secret_token: "60f7888bd025343e8b1d82e002446c263cd1329425904ef1a7ba4a919f2c05a5"
  signature_expiration: 3600 # one hour
