# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3be75524b381df3fc4b0ad035edbf3111b7558bcb061c227df11b34ba6481ef53e669d54fe0a7cb73d7c8de9179c605c24a593636fc2db691b1766a63ccab10
facebook_app_id: 1694045107582713
facebook_app_secret: e5abbd68931e35bf251f344e8d80d927
twitter_app_id: s67bNzvzQZhs8tnpya0ndZXu7
twitter_app_secret: tvfXE3EXWIzivO5er7FCSVGr4BesezMJmlUphh3tnE0WEaVbyr
test:
  secret_key_base: 9c3e009d24676edd55c89611c6bff7e18c0227f2a65b3d74a8c860a98e127299df33ab1ca293ce315621bb694670bcedd94dadaa5ad4e435ba94de9b0da9ae71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
