development:
  mysql41: 9312
  morphology: stem_en
  morphology: stem_ru
test:
  mysql41: 9313
production:
  mysql41: 9312
  morphology: stem_en
  morphology: stem_ru
  pid_file: /home/thinknetika/qa_thinknetika_app/shared/tmp/searchd.pid
  indices_location: /home/thinknetika/qa_thinknetika_app/shared/db/sphinx
  configuration_file: /home/thinknetika/qa_thinknetika_app/shared/production.sphinx.conf
  binlog_path: /home/thinknetika/qa_thinknetika_app/shared/binlog
  